### ISSUE TITLE
npm install issue

### ISSUE THREAD

**Issue by Karnith** [ArrayKnight/storybook-addon-headless#15]
**Describe the bug**
Can't install 2.0.0 of module

**To Reproduce**

npm install storybook-addon-headless

**Expected behavior**
module to install

**Screenshots**

**Desktop (please complete the following information):**

-   OS: [e.g. iOS]: windows 10

**Additional context**

npm ERR! code ENOENT
npm ERR! syscall chmod
npm ERR! path E:\CameoEarth\node_modules\storybook-addon-headless\node_modules\json5\lib\cli.js
npm ERR! errno -4058
npm ERR! enoent ENOENT: no such file or directory, chmod 'E:\CameoEarth\node_modules\storybook-addon-headless\node_modules\json5\lib\cli.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

**Comment by ArrayKnight** [comment]
@Karnith so far I've been unable to replicate this issue. Would you mind sharing:

- Node version
- NPM version
- Terminal / command line of choice and version if applicable

In the meantime, consider deleting your node_modules folder and package-lock.json and try to fresh install

**Comment by ArrayKnight** [comment]
While my project doesn't directly rely on `json5` as a dependency, several of my dependencies do. Mainly, `@babel/core`, `@storybook/core` and `ts-jest`. Only `@storybook/core` is a non-dev dependency, and I just published version **2.0.1**, which upgrades Storybook to it's latest version of 6.0.12

Can you let me know which version of Storybook you're using, please?

**Comment by Karnith** [comment]
@ArrayKnight sure:

- Node version - v13.11.0
- NPM version - 6.14.4
- Terminal / command line of choice and version if applicable - MINGW64_NT-10.0-18363 3.1.6-340.x86_64 2020-07-09 14:33 UTC x86_64 Msys

**Comment by Karnith** [comment]
> While my project doesn't directly rely on `json5` as a dependency, several of my dependencies do. Mainly, `@babel/core`, `@storybook/core` and `ts-jest`. Only `@storybook/core` is a non-dev dependency, and I just published version **2.0.1**, which upgrades Storybook to it's latest version of 6.0.12
> 
> Can you let me know which version of Storybook you're using, please?

modules for storybook:

- "@babel/core": "^7.11.1",
- "@pankod/pankod-cli": "^1.0.1",
- "@storybook/addon-actions": "^6.0.10",
- "@storybook/addon-essentials": "^6.0.10",
- "@storybook/addon-links": "^6.0.10",
- "@storybook/svelte": "^6.0.10",

**Comment by Karnith** [comment]
I used the npx sb init to auto configure

**Comment by Karnith** [comment]
I'll try with updating my modules with ncu and report back. I've deleted the package-lock.json.

**Comment by Karnith** [comment]
hmm. interesting. I was able to install now. thanks.

**Comment by ArrayKnight** [comment]
Excellent, glad it's been resolved
