### ISSUE TITLE
Question: rest api data on components

### ISSUE THREAD

**Issue by Karnith** [ArrayKnight/storybook-addon-headless#17]
Hi, I have a quick question. Can this module be used as a trigger action for components like buttons? What I'm trying to do is use storybook as a quasi visual api test bed for back end api without current front end. Later it will be used for component documentation.

**Comment by ArrayKnight** [comment]
No, there's currently no way for the story component to trigger an API call. You can however utilize the `autoFetchOnInit` parameter to make the API call automatically on story load.

I would suggest looking into [Swagger](https://swagger.io/) for purely API documentation with the ability to run test queries
