### ISSUE TITLE
Module not found: Error: Can't resolve 'storybook-addon-headless/register'

### ISSUE THREAD

**Issue by asteurba** [ArrayKnight/storybook-addon-headless#18]
**Describe the bug**
Can't start Storybook with storybook-addon-headless/register as an addon, while running storybook as a package in a Lerna setup with CRA in a second package. 
The storybook-addon-headless folder in node_modules only contains 3 files: LICENSE, package.json and README.md.

Full error: 
ERROR in ./.storybook/addons.js
Module not found: Error: Can't resolve 'storybook-addon-headless/register' in '/home/user/development/work/Pointbreak/reactjs-app/packages/library/.storybook'
 @ ./.storybook/addons.js 1:0-43
 @ multi /home/user/development/work/Pointbreak/reactjs-app/node_modules/@storybook/react/node_modules/@storybook/core/dist/server/common/polyfills.js ./.storybook/addons.js /home/user/development/work/Pointbreak/reactjs-app/node_modules/@storybook/react/node_modules/@storybook/core/dist/client/manager/index.js ./.storybook/generated-refs.js

**To Reproduce**
Create a lerna setup with Storybook in a package.
run yarn add storybook-addon-headless in the root of the package
start storybook

**Expected behavior**
Storybook starts

**Desktop (please complete the following information):**

-   OS: Ubuntu
-   Browser [e.g. chrome, safari]
-   Version 18.04

**Comment by ArrayKnight** [comment]
Would you mind providing a minimal setup? Either a public repo or copy in the contents of your package & lerna json files, please

**Comment by ArrayKnight** [comment]
It would also be helpful to know which version you're attempting to use

**Comment by ArrayKnight** [comment]
@asteurba

**Comment by asteurba** [comment]
@ArrayKnight hi, sorry, have been busy with other stuff the past week. I'll try to provide you with a minimal setup as soon as I have time.

**Comment by ArrayKnight** [comment]
I did a quick evaluation of the versions that are currently published:
![image](https://user-images.githubusercontent.com/5431637/93621642-b8d82000-f990-11ea-8fb3-aa52e8e07a3e.png)

It appears that versions 1.0.0 and 1.1.0 both have no executable code in them. I've requested that NPM unpublish these two versions.

If you're using Storybook v5 you should use version 1.5.3
If you're using Storybook v6 you should use version 2.0.1

@asteurba Let me know if this addresses your issue

**Comment by ArrayKnight** [comment]
Versions 1.0.0 & 1.1.0 have been unpublished
