### ISSUE TITLE
'can't convert undefined to object' error on rendering.

### ISSUE THREAD

**Issue by Mrostgaard** [ArrayKnight/storybook-addon-headless#21]
**Describe the bug**
After trying to get started i get the error:
**'can't convert undefined to object'**
whenever i try to access a component.

main.js 
```
module.exports = {
  stories: ["../src/stories/**/*.stories.(ts|tsx|js|jsx|mdx)"],
  addons: [
    '@storybook/preset-create-react-app',
    '@storybook/addon-actions',
    '@storybook/addon-links',
    '@storybook/addon-viewport',
    'storybook-addon-styled-component-theme/dist/register',
    'storybook-addon-headless/dist/register',
    {
      name: "@storybook/addon-docs",
      options: {
        configureJSX: true
      }
    }
  ],
};
```

preview.js
```
import { addDecorator, configure } from '@storybook/react';
import { withHeadless } from 'storybook-addon-headless';
import { withThemesProvider } from 'storybook-addon-styled-component-theme';
import ThemeProvider from './theme-provider';

import LightTheme from '../src/style/themes/light';
import DarkTheme from '../src/style/themes/dark';

const themes = [LightTheme, DarkTheme];
addDecorator(withThemesProvider(themes, ThemeProvider));
addDecorator(withHeadless({
    restful: {
        base: 'http://127.0.0.1:8000/',
        query: ""
    }
}));

```

**To Reproduce**

Copy main.js and preview details. 

**Expected behavior**
Hopefully no errors

**Comment by ArrayKnight** [comment]
I'm going to need more details about which versions of React, Storybook and this addon you've got installed.

Also it would be good to get this reproduced in isolation (no other addons, a single component, etc) to really help narrow down the issue.

I've also just published version 2.1.0 which you may wish to give a try. There's some additional error boundaries in place that might help identify where something is failing.

**Comment by Mrostgaard** [comment]
@ArrayKnight 
So updating it didn't work but i tried to install a new react project the same way i did the old one. The setup is as follows:

**Create react app:**
`npx create-react-app tmp --template typescript`

**Get storybook into the project:**
npx -p @storybook/cli sb init --story-format=csf-ts

**Add storybook-add-headless (v 2.1.0)** 
`yarn add storybook-addon-headless`

**.storybook/main.js**
```
module.exports = {
  "stories": [
    "../src/**/*.stories.mdx",
    "../src/**/*.stories.@(js|jsx|ts|tsx)"
  ],
  "addons": [
    "@storybook/addon-links",
    "@storybook/addon-essentials",
    "@storybook/preset-create-react-app",
    "storybook-addon-headless"
  ]
}
```

**.storybook/preview.js**
```
import { addDecorator } from '@storybook/react';
import { withHeadless } from 'storybook-addon-headless';

addDecorator(withHeadless({
    restful: {
        base: 'http://127.0.0.1:8000/',
        query: ""
    }
}));
```

The problem is that this still doesn't work. The error is still the same: 
`can't convert undefined to object`

**Comment by ArrayKnight** [comment]
The issue is the missing parameters within each story:
```
export default {
  title: 'Example/Page',
  component: Page,
  parameters: { // <!-- Add this
    headless: {}
  }
} as Meta;
```

Though this shouldn't be required so I'll be sure to post a fix soon. For now just add `parameters: { headless: {} }` to the default export in each of your stories

**Comment by ArrayKnight** [comment]
@Mrostgaard Thank you for you assistance in identifying this issue

**Comment by Mrostgaard** [comment]
Thank you so much for the swift responses and fixes. It is loading perfectly now. :raised_hands:
